### ISSUE TITLE
Stream Note Feature Request

### ISSUE THREAD

**Issue by antgiant** [mercdev-corp/streamnote-site#1]
I love Stream Note! It has been very helpful for me! I do have on feature request for it though. Hopefully this is the right way to submit it.

Can you please let add the ability to shift the time of all the time stamps.
I often start the Stream Note session at a different time as the actual video. So, All of the times are offset by the same amount. It would be great if I could shift all the times forward or backwards to line up with the times the video recording has. 

Thank you for considering this feature request

**Comment by qnub** [comment]
Thank you for using my application. And i agree - it's nice feature. I even need it myself, but somehow not thought to add it as feature to Stream Note. I'll implement it asap!

**Comment by antgiant** [comment]
Thank you!

**Comment by qnub** [comment]
Now should be available in store

**Comment by qnub** [comment]
Think i will rephrase it, but it works now too.  🙃

**Comment by antgiant** [comment]
Thank you so much! This is amazing!

Very much appreciated!
